image: node:alpine

cache: &global_cache
  paths:
    - node_modules/

stages:
  - install
  - lint
  - build
  - test
  - publish

install:
  stage: install
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds

build:
  stage: build
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn build
  artifacts:
    public: false
    paths:
      - types/lib
      - server/dist
      - core/lib
    expire_in: 1h

publish:
  stage: publish
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn build
    - yarn publish:all
  only:
    - master

lint-cli:
  stage: lint
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn lint:cli

lint-client:
  stage: lint
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn lint:client

lint-core:
  stage: lint
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn lint:core

lint-plugin:
  stage: lint
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn lint:plugin

lint-server:
  stage: lint
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn lint:server

lint-types:
  stage: lint
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn lint:types

test-cli:
  stage: test
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn test:cli

test-client:
  stage: test
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn test:client

test-core:
  stage: test
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn test:core

test-plugin:
  stage: test
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn test:plugin

test-server:
  stage: test
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn test:server

test-handling:
  stage: test
  cache:
    <<: *global_cache
  script:
    - yarn install --immutable --skip-builds
    - yarn test:handling

