yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
npmScopes:
  microlambda:
    npmAlwaysAuth: true
    npmPublishRegistry: https://registry.npmjs.org
    npmRegistryServer: https://registry.npmjs.org
