image: node:lts-alpine

reference:
  steps:
    - step: &testCLI
        name: 'Test and build CLI'
        script:
          - npm i
          - npx lerna bootstrap
          - npx lerna run lint --scope=@microlambda/cli
          - npx lerna run test --scope=@microlambda/cli
          - npx lerna run build --scope=@microlambda/cli

pipelines:
  pull-requests:
    '**':
      - step: *testCLI
  branches:
    master:
      - step: *testCLI
    next:
      - step: *testCLI
